apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  interval: 30m
  chart:
    spec:
      chart: base
      version: "1.22.0"
      sourceRef:
        kind: HelmRepository
        name: istio
      interval: 12h
  values:
    installCRDs: true
    
    tolerations:
    - key: os
      operator: Equal
      value: Windows
      effect: NoSchedule


