apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  interval: 5m
  dependsOn:
    - name: istio-base
      namespace: istio-system
  chart:
    spec:
      chart: istiod
      version: "1.22.0"
      sourceRef:
        kind: HelmRepository
        name: istio
      interval: 12h
  values:
    tolerations:
    - key: os
      operator: Equal
      value: Windows
      effect: NoSchedule
    installCRDs: true
    autoscaling:
      enabled: false

    global:
      istioNamespace: istio-system
      logging:
        #level: "default:info"
        level: "default:debug"
      configValidation: true




  





        

      
      