---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-apps
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/apps/
  prune: true
  wait: true
  postBuild:
    substitute:
      var_substitution_enabled: "true"
      #cluster_env: "prod"
      #cluster_region: "ca-central-1"
      cluster_name: "cluster1"



